### ISSUE TITLE
Resizing The Captcha's Image

### ISSUE THREAD

**Issue by NotMarx** [HaileyBot/captcha-generator#4]
# Resizing The Captcha's Image,

Hi there,
I would likely want to know how I can resize the Captcha's image from its width and height and the text is in the middle! Cause' It would be better for my bot if it gave smaller image rather than big. If anyone had an idea to this, please kindly help me. I had and currently finding a way to resize it but it does not work that well.

Thank you!

---
# Tried Some Way But Not Works Well As I'm Suck At Canvas.

![Example](https://cdn.discordapp.com/attachments/779256090873298984/791604462153629716/unknown.png)

Any useful help is appreciated :)

**Comment by cheesits456** [comment]
Just released a little update, one of the new features is configurable image height - check the updated `README.md` file for more info about how to do it.

Lemme know if this help

**Comment by NotMarx** [comment]
Sorry for the late reply. Just wanna say thanks for that! It'd help me, thanks!

**Comment by highjump0615** [comment]
Can you make height available for smaller? It is 250 as minimum currently, and it may be needed to show in flat place. Thanks.
